BEGIN;


INSERT INTO "CustomGuidesHeader" VALUES(1,'Arctic Explosion',1,18,'','http://settlersonlinewiki.eu/maps/mapaeksplozja01en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(2,'Dark Brotherhood',0,18,NULL,NULL);
INSERT INTO "CustomGuidesHeader" VALUES(3,'Valiant Little Tailor',0,18,NULL,NULL);
INSERT INTO "CustomGuidesHeader" VALUES(4,'Ali YWC',1,18,'','http://settlersonlinewiki.eu/maps/mapadrwal03en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(5,'Bandits Nest',0,18,NULL,NULL);
INSERT INTO "CustomGuidesHeader" VALUES(6,'Tomb Raiders',1,18,NULL,NULL);
INSERT INTO "CustomGuidesHeader" VALUES(7,'Ali YWC Ultra Slow',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(8,'DB',0,20,NULL,NULL);
INSERT INTO "CustomGuidesHeader" VALUES(30,'grrr 22',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(31,'Dark Bro Quick Loot',1,18,'','http://settlersonlinewiki.eu/maps/mapabractwo03en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(32,'VLT quicker',0,18,'','http://settlersonlinewiki.eu/maps/mapadzielny03en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(33,'Clever Tailor',0,18,'','http://settlersonlinewiki.eu/maps/mapasprytny04en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(34,'Tomb Raiders',1,26,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(35,'Lakeside',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(36,'VLT - YGG X 2  - OGG - MMA - ',0,'null','',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(37,'VLT - YGG X 2  - OGG - MMA - ',0,'null','',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(38,'YWC  BORIS  STEADFAST   OGG   MARY XMAS',0,'null','',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(39,'ALI YWC part 2',0,18,'','http://settlersonlinewiki.eu/maps/mapadrwalen.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(40,'Bastile Island',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(41,'Bastile Island',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(42,'Ali First Thief',0,18,'','http://settlersonlinewiki.eu/maps/mapazlodziej06en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(43,'Ali Second',0,18,'','http://settlersonlinewiki.eu/maps/mapazlodziej11en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(45,'Ali Third',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(46,'TOK',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(47,'Outlaws',0,18,'','http://settlersonlinewiki.eu/maps/mapabanici04en.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(48,'CLT',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(49,'CLT',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(50,'TOW',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(51,'TOW',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(52,'Roaring Bull quick loot',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(53,'Roaring Bull quick loot',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(54,'Fisherman',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(55,'Hansel',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(56,'Red Riding',0,18,'',NULL);
INSERT INTO "CustomGuidesHeader" VALUES(57,'Dark Priests',0,18,'','http://settlersonlinewiki.eu/maps/mapakaplani04.jpg');
INSERT INTO "CustomGuidesHeader" VALUES(58,'1599604650306',0,18,'',NULL);
/* COMMIT; */
